//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type Book = $ModelResult<$Schema, "Book">;
export type Member = $ModelResult<$Schema, "Member">;
export type Borrowing = $ModelResult<$Schema, "Borrowing">;
export type Auth = $TypeDefResult<$Schema, "Auth">;
export const BorrowingStatus = $schema.enums.BorrowingStatus.values;
export type BorrowingStatus = (typeof BorrowingStatus)[keyof typeof BorrowingStatus];
