import os
from temporalio import activity
from github import Github
from typing import Dict # Import Dict for type hinting

@activity.defn
async def github_activity(input_data: Dict) -> str:
    """
    Temporal activity to create a GitHub repository, push generated files, and open a PR.
    Accepts input_data dictionary containing 'files' and 'project_name'.
    """
    files = input_data.get("files", {})
    project_name = input_data.get("project_name", "default-project") # Provide a default for safety

    activity.logger.info(f"Starting GitHub activity for project: {project_name}")

    github_token = os.getenv("GITHUB_TOKEN")
    if not github_token:
        raise ValueError("GITHUB_TOKEN environment variable not set.")

    g = Github(github_token)
    user = g.get_user()

    repo_name = f"saas-{project_name}"
    
    # Check if repo already exists to avoid errors
    try:
        repo = user.get_repo(repo_name)
        activity.logger.info(f"Repository '{repo_name}' already exists. Skipping creation.")
    except Exception: # github.UnknownObjectException if repo doesn't exist
        repo = user.create_repo(repo_name, private=True, description=f"SaaS application generated by Agent Factory for {project_name}")
        activity.logger.info(f"Repository '{repo_name}' created successfully.")

    # --- Branch and File Pushing Logic ---
    main_branch_name = repo.default_branch

    # Check if the repo is empty by trying to get the main branch
    try:
        repo.get_branch(main_branch_name)
        is_empty = False
    except Exception: # github.UnknownObjectException
        is_empty = True

    # If the repo is empty, create an initial commit on the main branch
    if is_empty:
        # A README is a good first file
        readme_content = f"# SaaS Product: {project_name}\n\nThis repository was generated by the Factory Nexus AI Agent."
        if "README.md" not in files:
            files["README.md"] = readme_content
        
        # The first file needs to be created on the default branch to initialize it
        first_file_path = next(iter(files))
        first_file_content = files.pop(first_file_path)
        
        try:
            repo.create_file(
                first_file_path, 
                f"Initial commit: {first_file_path}", 
                first_file_content, 
                branch=main_branch_name
            )
            activity.logger.info(f"Initialized repo with {first_file_path} on {main_branch_name}.")
        except Exception as e:
            activity.logger.error(f"Failed to create initial file: {e}")
            raise

    # Now that the main branch is guaranteed to exist, create the 'dev' branch if it doesn't exist
    activity.logger.info("Checking if 'dev' branch exists...")
    try:
        repo.get_branch("dev")
        activity.logger.warning("Branch 'dev' already exists. Skipping creation.")
    except Exception: # github.UnknownObjectException
        activity.logger.info("'dev' branch not found. Creating it now...")
        main_branch = repo.get_branch(main_branch_name)
        repo.create_git_ref(ref=f"refs/heads/dev", sha=main_branch.commit.sha)
        activity.logger.info("Created 'dev' branch from main branch.")

    # Push all remaining files to the 'dev' branch
    for path, content in files.items():
        try:
            # Check if file exists to decide between create or update
            contents = repo.get_contents(path, ref="dev")
            repo.update_file(contents.path, f"Update {path}", content, contents.sha, branch="dev")
            activity.logger.info(f"Updated file: {path} in 'dev' branch.")
        except Exception: # github.UnknownObjectException
            repo.create_file(path, f"Create {path}", content, branch="dev")
            activity.logger.info(f"Created file: {path} in 'dev' branch.")
    
    # Open a Pull Request from 'dev' to main branch
    activity.logger.info(f"Checking for existing PRs from 'dev' to '{main_branch_name}'...")
    # Check for existing PRs from 'dev' to main
    open_prs = repo.get_pulls(state="open", head="dev", base=main_branch_name)
    if open_prs.totalCount > 0:
        pr = open_prs[0]
        activity.logger.warning(f"An open Pull Request from 'dev' to '{main_branch_name}' already exists: {pr.html_url}. Skipping creation.")
        return {"pr_url": pr.html_url, "repo_url": repo.html_url}
    
    activity.logger.info("No existing PR found. Creating a new one...")
    try:
        pr = repo.create_pull(
            title=f"feat: Initial code generation for {project_name}",
            body="This PR contains the initial full-stack code generated by the Factory Nexus AI development agent.",
            base=main_branch_name,
            head="dev"
        )
        activity.logger.info(f"Pull Request created: {pr.html_url}")
        return {"pr_url": pr.html_url, "repo_url": repo.html_url}
    except Exception as e:
        activity.logger.error(f"Failed to create Pull Request: {e}")
        # If PR creation fails for other reasons, return the repo URL as a fallback.
        return {"pr_url": pr.html_url, "repo_url": repo.html_url}
