import os
from temporalio import activity
from github import Github

@activity.defn
async def github_activity(files: dict, project_name: str) -> str:
    """
    Temporal activity to create a GitHub repository, push generated files, and open a PR.
    """
    activity.logger.info(f"Starting GitHub activity for project: {project_name}")

    github_token = os.getenv("GITHUB_TOKEN")
    if not github_token:
        raise ValueError("GITHUB_TOKEN environment variable not set.")

    g = Github(github_token)
    user = g.get_user()

    repo_name = f"saas-{project_name}"
    
    # Check if repo already exists to avoid errors
    try:
        repo = user.get_repo(repo_name)
        activity.logger.info(f"Repository '{repo_name}' already exists. Skipping creation.")
    except Exception: # github.UnknownObjectException if repo doesn't exist
        repo = user.create_repo(repo_name, private=True, description=f"SaaS application generated by Agent Factory for {project_name}")
        activity.logger.info(f"Repository '{repo_name}' created successfully.")

    # Create a 'dev' branch
    default_branch = repo.get_branch(repo.default_branch)
    try:
        repo.create_git_ref(ref=f"refs/heads/dev", sha=default_branch.commit.sha)
        activity.logger.info("Created 'dev' branch.")
    except Exception as e:
        activity.logger.warning(f"Could not create 'dev' branch (it might already exist): {e}")

    # Push files to 'dev' branch
    for path, content in files.items():
        try:
            # Check if file exists to decide between create or update
            contents = repo.get_contents(path, ref="dev")
            repo.update_file(contents.path, f"Update {path} from Agent Factory", content, contents.sha, branch="dev")
            activity.logger.info(f"Updated file: {path} in 'dev' branch.")
        except Exception: # github.UnknownObjectException if file doesn't exist
            repo.create_file(path, f"Initial commit: {path} from Agent Factory", content, branch="dev")
            activity.logger.info(f"Created file: {path} in 'dev' branch.")
    
    # Open a Pull Request from 'dev' to 'main'
    try:
        pr = repo.create_pull(
            title=f"Initial code for {project_name} from Agent Factory",
            body="This PR contains the initial code generated by the Dev Agent of the Agent Factory.",
            base=repo.default_branch, # Usually 'main'
            head="dev"
        )
        activity.logger.info(f"Pull Request created: {pr.html_url}")
        return pr.html_url
    except Exception as e:
        activity.logger.error(f"Failed to create Pull Request: {e}")
        # If PR creation fails, still return repo URL if files were pushed
        return repo.html_url if repo else "Failed to create repository or PR."
